[GK-16] Create alamofire network manager
Sonata-Girl/GIFKeeper pull request #15
Opened 2023-11-08 14:41 UTC by ArtyZenk

Create alamofire network manager

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Models/Model.swift
> +    let type: TypeEnum?
Все не может быть опциональным) Исправить это надо ты шо)

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Models/Model.swift
> +    let onload, onclick, onsent: Onclick?
В Swift так не пишут) - отдельно делай каждую

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Models/Model.swift
> +    let downsized, downsizedLarge, downsizedMedium: The480_WStill?
Убрать ненужные опшионалы и разделить переменные на 1 строка = 1 переменная

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Models/Model.swift
> +//  GIFKeeper
Название странное - Models/Model и содержит внутри все - так лучше не делать, лучше паовыносить вложенные структуры на файл и добавить все их в одну папку Models

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +enum Link: String {
enum Link: String {
    case trending, search, random
    
    static let apiKey = ["api_key": "nDUgO92yiVJQvP8TuJIjqkUueEn3vkUU"]
    static let baseURL = "https://api.giphy.com/v1/gifs/"

    var fullURL: String { Link.baseURL + self.rawValue }
}

2023-11-09 06:22 UTC, SomeStay07 commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +        AF.request(url, parameters: parameters)
Можно не выносить в отдельно parameters - тк один раз используешь

2023-11-09 07:33 UTC, Sonata-Girl requested changes

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +//  Model.swift
коммент Model, внизу название другое

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +struct Gifs: Codable {
Почему Codable? Мы обратно разве будем передавать?

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +struct Datum: Codable {
Тут тоже

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +struct Looping: Codable {
аналогично, почему Codable везде?

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +struct Datum: Codable {
Не оч понятное название. К чему относится , какие данные там содержатся ?

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +    let analytics: Analytics?
на мне нужны будут абсолютно все поля, довольно много ненужных

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Models/Model.swift
> +struct User: Codable {
думаю лишнее. это вроде данные человека, который загрузил гиф в интернет. Зачем?

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +                    decoder.keyDecodingStrategy = .convertFromSnakeCase
если используешь эту строку для чего тогда много кода в моделях CodingKeys: String, CodingKey { ?

2023-11-09 07:33 UTC, Sonata-Girl commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +    func fetchData<T: Decodable>(
а что мы получаем в этом методе? 
или это заготовка пока?

2023-11-10 10:12 UTC, ArtyZenk commented on GIFKeeper/Sources/Models/Model.swift
> +struct Datum: Codable {
Если изменить, то данные не приходят(

2023-11-10 15:56 UTC, SomeStay07 commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +enum NetworkError: Error {
Вынести в отдельный файл, сделать папку Networking и туда все слкадывать.

2023-11-10 15:56 UTC, SomeStay07 commented on GIFKeeper/Sources/Services/NetworkManager.swift
> +enum Link: String {
Вынести в отдельный файл - роздать можно NetworkAPI

2023-11-10 16:24 UTC, SomeStay07 approved these changes

2023-11-15 10:01 UTC, merged