[GK15] Added settings screen + settings cell
Sonata-Girl/GIFKeeper pull request #16
Opened 2023-11-19 15:32 UTC by Sonata-Girl

2023-11-19 15:55 UTC, ArtyZenk requested changes

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    }()
label.contentMode = .left проверь, но вроде по умолчанию и так left

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @available(*, unavailable)
шо це?

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +    private let userDefaults = UserDefaults.standard
userDefaults должен быть в сервисах (убери пока вообще его)

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +    }
пустая строка

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +}
пустая строка

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +        }
в одну строчку можно

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +// MARK: - Setup hierarchy
лишняя строка

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +
аналогично, тут не место user default (давай вынесем в отдельную задачу)

2023-11-19 15:55 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        }
AnyType -> T

Выглядит страшновато) Слишком много if

2023-11-20 07:47 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        }
Да, выглядит страшновато. но через Switch еще страшнее с приведением типа.
Есть предложения?)

2023-11-20 07:53 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @objc private func linkPressed() {
Название не совсем корректное, т.е ты пишешь "линка нажата", но по факту у тебя происходит следующее:
Нажимается ссылка и открывается диплинка. Можно поступить:
1. оставить тут linkPressed
2. Вынести if let url = value as? URL, в функцию, куда приходит значение и проверяется и открывается, а назвать эту функцию "openLink", что будет корректнее чем сейчас

переименовать функцию в openLink, но тоже, будет не совсем корректно

2023-11-20 07:53 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        value.snp.makeConstraints {
Отступы не забываем в одну строчку после каждой заканчивающиеся скобки!

2023-11-20 07:55 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        }
На самом деле, можно применить паттерн Стратегия, если у тебя получится.

2023-11-20 07:56 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        }
У switch будет два преимущества:
1 - Его проще будет читать
2 - Не надо приводить типы, а юзать is

2023-11-20 07:56 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    static let indentUI = 10
Если-честно, название вообще ничего не говорит, а что означает indentUI? :D

2023-11-20 07:56 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +
В одну строчку если пустое, т.е pressed() {}

2023-11-20 07:56 UTC, SomeStay07 commented on GIFKeeper/Sources/Scenes/Settings/SettingsViewController.swift
> +        return cell
return - отступ

2023-11-20 08:22 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/DetailVC/DetailGifViewController.swift
> +        textView.delegate = self
UIColor.lightGray.withAlphaComponent(Constants.halfOfPointAlpha).cgColor - Давай будет такие цвета выносить extension

2023-11-20 08:22 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +                    }
придирка, но все же не проще guard let value = value as? URL,  let url = URL(string: value.absoluteString) else { return }

2023-11-20 08:22 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    }
[view1, view2].forEach { view.addSubview($0) }

2023-11-20 11:10 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @available(*, unavailable)
Эт на другие iOS рассчитано , у нас вроде не затронет, уберу

2023-11-20 11:11 UTC, ArtyZenk commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @available(*, unavailable)
я это понимаю, но yagni не дремлет

2023-11-20 11:14 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @objc private func linkPressed() {
Про 2 -  у меня value это всегда Label , а не URL. Там эта проверка недоступна, поэтому проверяю на attributed

2023-11-20 11:15 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    @objc private func linkPressed() {
А если вынести просто отдельно это всё? 
    @objc private func linkPressed() {
        openLink()
    }

2023-11-20 11:17 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +    static let indentUI = 10
ну indent переводится как отступ. Отступ у меня одинаковый для всех UI элементов на экране, поэтому назвала ОтступUI ))

2023-11-20 11:21 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +                    }
ну кстати не придирка , чаще надо использовать гуард, но иногда почему то хочется написать if let

2023-11-20 12:37 UTC, Sonata-Girl commented on GIFKeeper/Sources/Scenes/Settings/Cell/SettingsCell.swift
> +        }
> На самом деле, можно применить паттерн Стратегия, если у тебя получится.

То есть, сделать разные ячейки на каждый случай?

2023-11-22 08:43 UTC, merged